"""Noise Protocol Framework (KKpsk2) transport for Sendspin."""

from aiosendspin.models.types import ServerErrorReason

from .constants import (
    ERROR_TYPE_SERVER,
    HANDSHAKE_TYPE,
    INIT_TYPE_CLIENT,
    INIT_TYPE_SERVER,
    MSG_TYPE_JSON_BODY,
    PROTOCOL_VERSION,
    PSK_ID_LABEL,
    SENTINEL_PSK,
)
from .driver import (
    DEFAULT_HANDSHAKE_TIMEOUT_S,
    HandshakeAbortedError,
    HandshakeResult,
    HandshakeWebSocket,
    InitRejectedError,
    PskProvider,
    PskResolver,
    run_handshake_client,
    run_handshake_server,
    run_rehandshake_client,
    run_rehandshake_server,
)
from .keys import (
    PEER_ID_SIZE,
    PSK_SIZE,
    Identity,
    b64url_decode,
    b64url_encode,
    generate_psk,
    psk_id_for,
)
from .models import (
    ClientInitMessage,
    ClientInitPayload,
    ClientPairFinalizeMessage,
    ClientPairFinalizePayload,
    NoiseHandshakeMessage,
    NoiseHandshakePayload,
    NoiseMsg1Payload,
    NoiseMsg2Payload,
    ServerErrorMessage,
    ServerErrorPayload,
    ServerInitMessage,
    ServerInitPayload,
    ServerPairFinalizeMessage,
    ServerPairFinalizePayload,
)
from .pairing import (
    InvalidPairingCodeError,
    PairingError,
    run_dynamic_pairing_code_client,
    run_dynamic_pairing_code_server,
    run_pairing_psk_client,
    run_pairing_psk_server,
    run_static_pairing_code_client,
    run_static_pairing_code_server,
)
from .pairing_code import format_pairing_code
from .pairing_token import (
    PSKPairingToken,
    decode_pairing_code_token,
    decode_psk_token,
    encode_pairing_code_token,
    encode_psk_token,
)
from .session import NoiseCipherSuite, NoiseSession
from .trust_store import (
    ClientPairingRecord,
    ClientPairingStore,
    FileClientPairingStore,
    FileServerPairingStore,
    InMemoryClientPairingStore,
    InMemoryServerPairingStore,
    PairingPsk,
    PskCategory,
    ResolvedPsk,
    ServerPairingRecord,
    ServerPairingStore,
    StagedPairingPsk,
    TrustedUnpairedClient,
)
from .wire import EncryptedWebSocket, RawWebSocket

__all__ = [
    "DEFAULT_HANDSHAKE_TIMEOUT_S",
    "ERROR_TYPE_SERVER",
    "HANDSHAKE_TYPE",
    "INIT_TYPE_CLIENT",
    "INIT_TYPE_SERVER",
    "MSG_TYPE_JSON_BODY",
    "PEER_ID_SIZE",
    "PROTOCOL_VERSION",
    "PSK_ID_LABEL",
    "PSK_SIZE",
    "SENTINEL_PSK",
    "ClientInitMessage",
    "ClientInitPayload",
    "ClientPairFinalizeMessage",
    "ClientPairFinalizePayload",
    "ClientPairingRecord",
    "ClientPairingStore",
    "EncryptedWebSocket",
    "FileClientPairingStore",
    "FileServerPairingStore",
    "HandshakeAbortedError",
    "HandshakeResult",
    "HandshakeWebSocket",
    "Identity",
    "InMemoryClientPairingStore",
    "InMemoryServerPairingStore",
    "InitRejectedError",
    "InvalidPairingCodeError",
    "NoiseCipherSuite",
    "NoiseHandshakeMessage",
    "NoiseHandshakePayload",
    "NoiseMsg1Payload",
    "NoiseMsg2Payload",
    "NoiseSession",
    "PSKPairingToken",
    "PairingError",
    "PairingPsk",
    "PskCategory",
    "PskProvider",
    "PskResolver",
    "RawWebSocket",
    "ResolvedPsk",
    "ServerErrorMessage",
    "ServerErrorPayload",
    "ServerErrorReason",
    "ServerInitMessage",
    "ServerInitPayload",
    "ServerPairFinalizeMessage",
    "ServerPairFinalizePayload",
    "ServerPairingRecord",
    "ServerPairingStore",
    "StagedPairingPsk",
    "TrustedUnpairedClient",
    "b64url_decode",
    "b64url_encode",
    "decode_pairing_code_token",
    "decode_psk_token",
    "encode_pairing_code_token",
    "encode_psk_token",
    "format_pairing_code",
    "generate_psk",
    "psk_id_for",
    "run_dynamic_pairing_code_client",
    "run_dynamic_pairing_code_server",
    "run_handshake_client",
    "run_handshake_server",
    "run_pairing_psk_client",
    "run_pairing_psk_server",
    "run_rehandshake_client",
    "run_rehandshake_server",
    "run_static_pairing_code_client",
    "run_static_pairing_code_server",
]
